name: Ocultar PayPal

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Poner clave secreta de PayPal
        run: |
          sed -i "s|PAYPAL_CLIENT_ID_PLACEHOLDER|${{ secrets.PAYPAL_CLIENT_ID }}|g" index.html
          
      - name: Publicar página
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
